In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
# list
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
# how to convert list to array

arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [10]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [11]:
np.arange(20,10) # 1st arg > 2nd arg

array([], dtype=int64)

In [12]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [13]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
# PARAMETER TUNING = what system given automatically  or default
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
# HYPER PARAMETER TUNING = if user change the system parameter
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [17]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones(5,dtype = int)

array([1, 1, 1, 1, 1])

In [25]:
np.ones((2,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
np.full((2,3),2,dtype = int)

array([[2, 2, 2],
       [2, 2, 2]])

In [34]:
np.random.rand(2)

array([0.07744817, 0.80284018])

In [36]:
np.random.rand(2,3)

array([[0.16254386, 0.22913785, 0.52653727],
       [0.14999319, 0.12115479, 0.41196593]])

In [38]:
np.random.randint(5)

4

In [42]:
np.random.randint(2,9)

7

In [46]:
np.random.randint(2,9,4 ) # generate numbers random from 2 to 9 exclude 9

array([8, 2, 2, 5], dtype=int32)

In [49]:
np.random.randint(10,40,(10,10 )) # 10*10 matrix

array([[14, 25, 38, 10, 27, 12, 29, 31, 23, 22],
       [14, 29, 18, 30, 20, 12, 10, 11, 35, 22],
       [30, 25, 34, 24, 11, 39, 38, 15, 24, 15],
       [20, 23, 10, 11, 28, 20, 31, 16, 11, 19],
       [30, 35, 33, 19, 31, 33, 37, 22, 28, 27],
       [33, 33, 34, 14, 13, 22, 30, 11, 32, 23],
       [19, 23, 20, 24, 34, 19, 27, 24, 33, 39],
       [12, 38, 34, 38, 21, 22, 17, 12, 35, 19],
       [26, 31, 21, 32, 29, 11, 22, 27, 11, 34],
       [13, 34, 24, 13, 27, 23, 19, 34, 14, 23]], dtype=int32)

In [50]:
arr1 = np.random.randint(10,40,(10,10 ))
print(arr1)

[[31 33 39 35 24 38 16 11 38 39]
 [15 33 14 38 29 15 24 36 24 31]
 [20 36 27 26 25 11 39 12 39 15]
 [13 35 26 22 18 28 12 38 11 16]
 [14 28 36 29 28 20 29 19 17 36]
 [25 15 16 28 12 13 37 36 10 33]
 [38 20 26 37 23 35 26 10 26 30]
 [26 14 35 28 25 30 25 16 32 25]
 [24 25 23 33 31 21 23 25 21 34]
 [38 25 29 29 35 37 22 23 20 38]]


In [53]:
arr1[2]

array([20, 36, 27, 26, 25, 11, 39, 12, 39, 15], dtype=int32)

In [54]:
arr1[2]

array([20, 36, 27, 26, 25, 11, 39, 12, 39, 15], dtype=int32)

In [56]:
arr1[-2]

array([24, 25, 23, 33, 31, 21, 23, 25, 21, 34], dtype=int32)

In [57]:
arr1[0:3]

array([[31, 33, 39, 35, 24, 38, 16, 11, 38, 39],
       [15, 33, 14, 38, 29, 15, 24, 36, 24, 31],
       [20, 36, 27, 26, 25, 11, 39, 12, 39, 15]], dtype=int32)

In [58]:
arr1[0:6:2]

array([[31, 33, 39, 35, 24, 38, 16, 11, 38, 39],
       [20, 36, 27, 26, 25, 11, 39, 12, 39, 15],
       [14, 28, 36, 29, 28, 20, 29, 19, 17, 36]], dtype=int32)

In [59]:
arr1[::-1]

array([[38, 25, 29, 29, 35, 37, 22, 23, 20, 38],
       [24, 25, 23, 33, 31, 21, 23, 25, 21, 34],
       [26, 14, 35, 28, 25, 30, 25, 16, 32, 25],
       [38, 20, 26, 37, 23, 35, 26, 10, 26, 30],
       [25, 15, 16, 28, 12, 13, 37, 36, 10, 33],
       [14, 28, 36, 29, 28, 20, 29, 19, 17, 36],
       [13, 35, 26, 22, 18, 28, 12, 38, 11, 16],
       [20, 36, 27, 26, 25, 11, 39, 12, 39, 15],
       [15, 33, 14, 38, 29, 15, 24, 36, 24, 31],
       [31, 33, 39, 35, 24, 38, 16, 11, 38, 39]], dtype=int32)

In [61]:
arr1[2,3]

np.int32(26)

In [62]:
arr1[0]

array([31, 33, 39, 35, 24, 38, 16, 11, 38, 39], dtype=int32)

In [67]:
arr1[0,2] = 100

In [68]:
arr1

array([[ 31,  33, 100,  35,  24,  38,  16,  11,  38,  39],
       [ 15,  33,  14,  38,  29,  15,  24,  36,  24,  31],
       [ 20,  36,  27,  26,  25,  11,  39,  12,  39,  15],
       [ 13,  35,  26,  22,  18,  28,  12,  38,  11,  16],
       [ 14,  28,  36,  29,  28,  20,  29,  19,  17,  36],
       [ 25,  15,  16,  28,  12,  13,  37,  36,  10,  33],
       [ 38,  20,  26,  37,  23,  35,  26,  10,  26,  30],
       [ 26,  14,  35,  28,  25,  30,  25,  16,  32,  25],
       [ 24,  25,  23,  33,  31,  21,  23,  25,  21,  34],
       [ 38,  25,  29,  29,  35,  37,  22,  23,  20,  38]], dtype=int32)

In [71]:
arr1[:,0]  # columns of 0

array([31, 15, 20, 13, 14, 25, 38, 26, 24, 38], dtype=int32)

In [72]:
arr1[:,-2]

array([38, 24, 39, 11, 17, 10, 26, 32, 21, 20], dtype=int32)

In [73]:
arr1

array([[ 31,  33, 100,  35,  24,  38,  16,  11,  38,  39],
       [ 15,  33,  14,  38,  29,  15,  24,  36,  24,  31],
       [ 20,  36,  27,  26,  25,  11,  39,  12,  39,  15],
       [ 13,  35,  26,  22,  18,  28,  12,  38,  11,  16],
       [ 14,  28,  36,  29,  28,  20,  29,  19,  17,  36],
       [ 25,  15,  16,  28,  12,  13,  37,  36,  10,  33],
       [ 38,  20,  26,  37,  23,  35,  26,  10,  26,  30],
       [ 26,  14,  35,  28,  25,  30,  25,  16,  32,  25],
       [ 24,  25,  23,  33,  31,  21,  23,  25,  21,  34],
       [ 38,  25,  29,  29,  35,  37,  22,  23,  20,  38]], dtype=int32)

In [75]:
arr1[0:3,0:3]

array([[ 31,  33, 100],
       [ 15,  33,  14],
       [ 20,  36,  27]], dtype=int32)

# Masking or filter in python

In [77]:
arr2 = np.random.randint(1,10,(5,10))

In [78]:
arr2

array([[7, 5, 5, 7, 9, 3, 2, 7, 4, 1],
       [1, 9, 3, 5, 8, 5, 6, 1, 9, 8],
       [5, 6, 5, 3, 7, 2, 3, 6, 2, 9],
       [2, 3, 3, 4, 4, 1, 3, 8, 1, 8],
       [9, 8, 7, 8, 8, 9, 7, 6, 3, 6]], dtype=int32)

In [79]:
arr2 > 5

array([[ True, False, False,  True,  True, False, False,  True, False,
        False],
       [False,  True, False, False,  True, False,  True, False,  True,
         True],
       [False,  True, False, False,  True, False, False,  True, False,
         True],
       [False, False, False, False, False, False, False,  True, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True]])

In [80]:
arr2[arr2 > 5]

array([7, 7, 9, 7, 9, 8, 6, 9, 8, 6, 7, 6, 9, 8, 8, 9, 8, 7, 8, 8, 9, 7,
       6, 6], dtype=int32)

In [81]:
arr2[arr2 == 5]

array([5, 5, 5, 5, 5, 5], dtype=int32)

In [82]:
arr2[arr2 != 5]

array([7, 7, 9, 3, 2, 7, 4, 1, 1, 9, 3, 8, 6, 1, 9, 8, 6, 3, 7, 2, 3, 6,
       2, 9, 2, 3, 3, 4, 4, 1, 3, 8, 1, 8, 9, 8, 7, 8, 8, 9, 7, 6, 3, 6],
      dtype=int32)

# reshape

In [83]:
arr

array([0, 1, 2, 3, 4, 5])

In [84]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
arr.reshape(4,3)

ValueError: cannot reshape array of size 6 into shape (4,3)

In [86]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [87]:
arr.reshape(4,1)

ValueError: cannot reshape array of size 6 into shape (4,1)

In [88]:
arr.max()

np.int64(5)

In [89]:
arr.min()

np.int64(0)

In [94]:
n = 10
for i in range(5):
    if i == 1:
        print('Hello')
        break
else:
    print('Num Not found')

Hello
