## Array Creation Functions

In [1]:
import numpy as np

In [2]:
# create an array froom a list
a  = np.array([1,2,3])
print('Array a:',a)

Array a: [1 2 3]


In [3]:
# create an array with evenly spaced values
b = np.arange(0,10,3)  # values from 0 to 10 with step 2
print('Array b:',b)

Array b: [0 3 6 9]


In [4]:
# craete array filled with zeros
d = np.zeros((2,3))  # 2x3 matrix of zeros
print('Array d:\n',d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# craete array filled with zeros
d = np.zeros((2,3),dtype = int)  # 2x3 matrix of zeros
print('Array d:\n',d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [6]:
# craete array filled with ones
e = np.ones((3,2))  # 2x3 matrix of ones
print('Array e:\n',e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# create an identiy matrix

f  = np.eye(4)  # 4x4 matrix
print('Indentity matrix f:\n',f)

Indentity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Array manipulation Functions()

In [8]:
# reshape array
a1= np.array([1,2,3])
reshaped = np.reshape(a1,(1,3)) # reshape to 1x3
print('Reshaped array:', reshaped)

Reshaped array: [[1 2 3]]


In [9]:
# reshape array
a1= np.array([1,2,3])
reshaped = np.reshape(a1,(3,1)) # reshape to 3x1
print('Reshaped array:\n', reshaped)

Reshaped array:
 [[1]
 [2]
 [3]]


In [10]:
# flatten array

f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1) # flatten to 1D arry
print('Falttedned array:',flattened)

Falttedned array: [ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# transpose array

e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1) # Transposed rray
print('Transposed Array:\n',transposed)

Transposed Array:
 [[1 3]
 [2 4]]


In [12]:
# stack array vertically

a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2]) # stack a and b vertically

print('Stacked Array:\n', stacked)

Stacked Array:
 [[1 2]
 [3 4]]


In [13]:
# stack array horizontal

a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2]) # stack a and b horizontal

print('Stacked Array:\n', stacked)

Stacked Array:
 [1 2 3 4]


## Math operations in Numpy

In [14]:
# add two arrays

g = np.array([1,2,3,4])
added = np.add(g,2) # add 2 each element
print('Added 2 to g:',added)

Added 2 to g: [3 4 5 6]


In [15]:
# square each element
g = np.array([1,2,3,4])
squared = np.power(g,2) #  square each element
print('squared to g:',squared)


squared to g: [ 1  4  9 16]


In [16]:
#  square root of  each element

g = np.array([1,2,3,4])
sqrt_val = np.sqrt(g) #  square root  each element
print('square root to g:',sqrt_val)


square root to g: [1.         1.41421356 1.73205081 2.        ]


In [17]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [18]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,g)  #dot product of a and g
print(' dot product of a and g:',dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [19]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [20]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,a3)  #dot product of a and a3
print(' dot product of a and a3:',dot_product)

 dot product of a and a3: 14


## statistical in numpy

In [21]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print('Mean of s:',mean)

Mean of s: 2.5


In [22]:
# variance of array
var = np.var(s)
print("Variance of s:",var)

Variance of s: 1.25


In [23]:
# standard deviation of array
std_dev = np.std(s)
print("standard deviation of s:",std_dev)

standard deviation of s: 1.118033988749895


In [24]:
s

array([1, 2, 3, 4])

In [25]:
# Minimum element of array
minimum = np.min(s)
print('Minimum of s:',minimum)

Minimum of s: 1


In [26]:
# Minimum element of array
maximum = np.max(s)
print('Max of s:',maximum)

Max of s: 4


## Linear Algebra Functions

In [27]:
#  Genearate random values between 0 and 1
random_vals = np.random.rand(3) # Array of 3 random values between 0 and 1
print('Random values:',random_vals)

Random values: [0.91767079 0.1815891  0.83154131]


In [28]:
# Genearate random ints
random_ints = np.random.randint(0,10,size=4) # Array of 4 random integers between 0 and 10
print('Random values:',random_ints)

Random values: [6 4 1 9]


In [29]:
# Set seed for reproductibility

np.random.seed(1)

# Genearate random ints
random_ints = np.random.randint(0,10,size=5) # Array of 5 random integers between 0 and 10
print('Random Integers:',random_ints)

Random Integers: [5 8 9 5 0]


## 7 Boolean & Logical Functions

In [30]:
# Check if all elements are True

# all
logical_test = np.array([True, False, True]) 
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [31]:
logical_test = np.array([True, True, True]) 
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: True


In [32]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [33]:
# Check if all elements are True
logical_test = np.array([False, True, False])
all_true = np.any(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: True


## 8. Set Operations

In [34]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [35]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


## 9. Array Attribute Functions

In [36]:
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


## 10.Other Functions

In [37]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [38]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [39]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
